include: .pipelines/base.gitlab-ci.yml

variables:
  TF_WORKSPACE: $TF_CLOUD_WORKSPACE
  TF_DIRECTORY: $CI_PROJECT_DIR
  TF_API_TOKEN: $TF_API_TOKEN
  TF_CLOUD_ORGANIZATION: $TF_CLOUD_ORGANIZATION
  
  PROJECT_PIPELINE_NAME: "Default pipeline name"
# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup
sast:
  stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml

workflow:
  name: "$PROJECT_PIPELINE_NAME"
  rules:
    # Default branch (e.g., 'main') - Non-speculative apply
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
      variables:
        PROJECT_PIPELINE_NAME: "$CI_DEFAULT_BRANCH pipeline"
        PLAN_ONLY: "false"
        SPECULATIVE: "false"
        SAVE_PLAN: "false"
        IS_DESTROY: "false"
    # Merge request (PR) - Plan only
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
      variables:
        PROJECT_PIPELINE_NAME: "Merge Request pipeline: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
        PLAN_ONLY: "true"
        SPECULATIVE: "true"
        SAVE_PLAN: "false"
        IS_DESTROY: "false"

# Upload configuration for the current workspace
upload_configuration:
  tags:
   - platform
  stage: ".pre"
  extends: .tfc:upload_configuration

# Create a Terraform run (plan or apply depending on the context)
create_run:
  tags:
   - platform
  stage: "build"
  extends: .tfc:create_run
  variables:
    MESSAGE: "LGTM"

# Apply Terraform run - Only on the default branch after a successful plan
apply_run:
  tags:
   - platform
  stage: "deploy"
  extends: .tfc:apply_run
  rules:
    # Only allow apply on the default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  # Do not apply for merge requests
      when: never


# Plan Output - Runs on merge requests (PRs)
plan_output:
  tags:
   - platform
  stage: "deploy"
  extends: .tfc:plan_output
  rules:
    # Run plan output only for merge requests
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Check run status - Only runs for merge requests
check_run_status:
  tags:
   - platform
  stage: ".post"
  script:
    - if [ "$run_status" != "planned_and_finished" ]; then exit 1; fi;
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
